name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branche source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build project
      run: npm install && npm run build  # Ajustez selon vos commandes de build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Répertoire de build
